name: Build & release bundle

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  release-lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn install

      - name: Fill in .env
        run: |
          echo 'USE_LOGGER=${{ vars.USE_LOGGER }}' > .env

      - name: Build types
        run: yarn build:types

      - name: Build dist
        run: yarn build:dist

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
