name: Build & release bundle

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  release-lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn install

      - name: Fill in .env
        run: |
          echo 'USE_LOGGER=${{ vars.USE_LOGGER }}' > .env

      - name: Build types
        run: yarn build:types

      - name: Build dist
        run: yarn build:dist

      - name: Create release folder
        run: |
          rm -rf release
          mkdir release
          cp -r build        release/
          cp -r types        release/
          cp -r example      release/
          cp -r licenses     release/
          cp    package.json release/
          cp    README.md    release/

      - name: Push to public repo
        env:
          TARGET_REPO: IATNAOD/react-canvas-workbench
          TARGET_BRANCH: main
          PAT: ${{ secrets.PUBLIC_REPO_PAT }}
          GIT_AUTHOR_NAME: IATNAOD
          GIT_AUTHOR_EMAIL: iatnaod@iatnaod.space
        run: |
          cd release
          git init -b $TARGET_BRANCH
          git remote add origin https://${PAT}@github.com/${TARGET_REPO}.git

          git fetch origin $TARGET_BRANCH --depth=1 || true
          git reset --mixed origin/$TARGET_BRANCH || true

          git add .

          if git diff --cached --quiet; then
            echo "No changes to publish"
            exit 0
          fi

          git -c user.name="$GIT_AUTHOR_NAME" -c user.email="$GIT_AUTHOR_EMAIL" \
              commit -m "Release ${{ github.ref_name }}"
          git push --set-upstream origin $TARGET_BRANCH

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
